Batfoxkid/Freak-Fortress-2-Rewrite

addons/sourcemod/scripting/ff2r_default_abilities.sp

KillTimer is basically considered deprecated and it should almost never be used. delete should be used instead.
Transformed client ids into user ids and viceversa in timers.
Furthermore, there was an oversight where the client id was made into an userid but never transformed back into a client id in Timer_RageTradeSpam.

Replace KillTimer with delete & sanitize timers

---

addons/sourcemod/scripting/freak_fortress_2/econdata.sp
addons/sourcemod/scripting/freak_fortress_2/stocks.sp
addons/sourcemod/scripting/freak_fortress_2/weapons.sp

Give the possibility to server owners to specify weapon attributes by name and not only by ID.
This does NOT apply to bosses as they use a different function. We should make the attribute parsing into their own functions so we don't have to rewrite the same logic in two different places.
I've also added a new stock: IsClientValid.
It's to avoid having a long line to check whether or not the client is valid.
#4

Named Attributes

---

addons/sourcemod/scripting/freak_fortress_2/weapons.sp

The only way to maintain attributes such as min_viewmodel_offset is to not remove them in the first place. We have to manually nullify all the static attributes the weapon has.
I've tested it and it works fine. Though, I have no way to properly test all the edge cases ( if they exist in the first place ).

Proper way to strip attributes

---

addons/sourcemod/scripting/freak_fortress_2.sp

This would cause TF_OnTakeDamage to get called twice since the logic of checking whether or not the library exists was messed up

Move SDKHook_LibraryAdded and ...Removed

---

addons/sourcemod/scripting/freak_fortress_2.sp
addons/sourcemod/scripting/freak_fortress_2/commands.sp
addons/sourcemod/scripting/freak_fortress_2/convars.sp
addons/sourcemod/scripting/freak_fortress_2/gamemode.sp

If the convar is enabled the last player on a team (bosses excluded) is highlighted to make it easier to move the end of the round along especially if the last player is hiding from the boss.

Add player glow to last player on team (configurable)

---

addons/sourcemod/scripting/freak_fortress_2/commands.sp

This Push fixes two issues:
1) Users were blocked to change to the another team while playing "Waiting for players" round
2) Users were allowed to change to the boss' team while pre-round
This is because a wild `!` lying around

Fixes bug allowing Red to change to Blu

---

addons/sourcemod/scripting/freak_fortress_2/attributes.sp
addons/sourcemod/scripting/freak_fortress_2/tf2utils.sp

i should point out that i didn't changed comment lines but Maximum overheal capacity for sanguise is now 260HP for 70HP Spy (+275%)

Fix for TF2U_GetMaxOverheal() and Attribute sanguise

---

addons/sourcemod/scripting/freak_fortress_2/bosses.sp

This is for software rendering which doesn't exist in tf2 anymore.
I also think you should make dx80.vtx optional as well instead of refusing to precache the whole model if it is missing.

Remove requirement for sw.vtx

---

addons/sourcemod/scripting/freak_fortress_2/weapons.sp

Force-A-Nature and Loose Cannon got `ubercharge rate penalty` attribute on each hit because `mod attribute hit stale` has wrong indexes size.
And I fixed a bug where the `critType` was not sending by reference.

Fix custom attributes aren't working

---

addons/sourcemod/scripting/freak_fortress_2/bosses.sp

freak_fortress_2: Don't rename plugins in 'optional' folder

---

addons/sourcemod/scripting/freak_fortress_2/bosses.sp

Basically only one of the played character sounds from the specified list is getting replaced.
I'm not sure why `ConfigMap.GetInt` returns false here. Maybe this needs further debugging.

freak_fortress_2: Fix 'catch_replace' being very broken

---

addons/sourcemod/scripting/freak_fortress_2/sdkhooks.sp

This resulted in boss playing catchphrases with funny pitch when hitting water. Trivial fix.

freak_fortress_2: Don't replace sounds when water splashing

---

addons/sourcemod/scripting/ff2r_menu_abilities.sp

**Before** the fix, the abilities were totally unresponsive. On pressing them nothing happens and the menu is ... pretty much useless.
After this fix, ability activation seems to work properly, although there's still like an extra mana being registered for use by abilities...
[Sample picture after fix.](https://steamuserimages-a.akamaihd.net/ugc/2099296363766292016/E2107187694E2E8AA340D46E9AF34E7D09413B4A/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false)
So there seems to be another issue here. Maybe it's related to the code on line 255 which is also referencing the wrong variable, however I cannot currently test this theory.
I guess I'll need a recommendation here. 
[Here's the config of the boss](https://paste.ee/p/AtbOR) in case there's issue you can spot …

ff2r_menu_abilities: Fix menu being very broken

---

addons/sourcemod/scripting/freak_fortress_2/bosses.sp

Old weapon hiding code is not working and on top of that changing `m_iWorldModelIndex` results in buggy firstperson animations when M1.
After experiments some time ago at Nec, we found that setting `rendermode` to `RENDER_ENVIRONMENTAL` hides weapon reliably and doesn't cause any other side effects.

freak_fortress_2: Fix weapon hiding not working

---

addons/sourcemod/scripting/freak_fortress_2/natives_old.sp

when called with `lang` = 0, aka almost all the time.

freak_fortress_2: Fix FF2_GetBossName erroring in IsClientInGame

---

addons/sourcemod/scripting/freak_fortress_2/bosses.sp

and that way minions summoned using `rage_cloneattack` having random class.

freak_fortress_2: Fix FF2R_CreateBoss not understanding "class" with string

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

For reference the relevant part of the config of the boss looks like:
```
"special_dropprop"
{
"model"	"models/weapons/c_models/c_buffalo_steak/c_buffalo_steak.mdl"
"remove ragdolls"	"1"
"plugin_name"	"ff2r_default_abilities"
}
"mod_precache"
{
"models/weapons/c_models/c_buffalo_steak/c_buffalo_steak.mdl" ""
}
```
Even though there's `mod_precache` section, the server still crashes due to this model not being precached.
I guess there's an issue with this section not functioning correctly (yes, I changed map/restarted server, but it won't work), however it won't hurt to preemptively precache the model before use, there won't be significant performance hit, I guess.

ff2r_default_abilities: Fix crash due to uncached model

---

addons/sourcemod/scripting/freak_fortress_2/bosses.sp

I missed that detail due to copypasting.

freak_fortress_2: Fix minion class fix being incomplete

---

addons/sourcemod/scripting/freak_fortress_2/music.sp

Some of our bosses use color tags so remove these when printing in the server or client console, as well as in menus.

freak_fortress_2: Remove color tags from bgm name and artist if not printing them on chat.

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

Scary point of this bug is that explosive dance will follow dead player.

ff2r_default_abilities: Fix explosive dance remaining after death

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

As mentioned in #98, If boss attacked before teleport, attack will preserve after teleport. It allow bosses to kill players right after teleport(You can easily do this with slow attack rate melee).
`dynamic_teleport` in sarysa's `ff2_dynamic_default.sp` make all damage to 0 during given duration, but I chose different way. I added "reset on attack" to prevent this by resetting charge.
In Addition, boss who has long stun duration is very weak after teleport. Because boss can't do anything while stun state. So, I added `flags` and `slowdown` options.

ff2r_default_abilities: Add more options to special_mobility

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

I forgot the exact details of how this fixes the issue.
I guess the logic is if we follow this sample:
```
"special_cbs_multimelee"
{
// Weapon indexes
"1"				"171"
"2"				"193"
"3"				"232"
"4"				"401"
"plugin_name"	"ff2r_default_abilities"
}
```
Without the fix `length` will be equal to 5, thus `GetURandomInt()` will return a number in the range 0 to 4 inclusive. But 4 is the index of "plugin_name" (out of range for our situation), so `GetInt()` will return default value of 0.
So decrease length so it's 4 and thus `GetURandomInt()` will return in range 0 to 3. `GetKey()` indexing starts from 0.
You get it.

ff2r_default_abilities: Fix CBS randomly getting Bat weapon

---

addons/sourcemod/scripting/freak_fortress_2/gamemode.sp

In detail:
- tf_logic_arena's `CapEnableDelay` is only used for setting tf_gamerules_data's `m_flCapturePointEnableTime` before arena round start.
- So, unlocking by alive check(`ff2_game_capture_alive`) actually unlock them if `ff2_game_capture_time` ConVar value was not setup(ex. 0.0)
- But if `ff2_game_capture_time` ConVar has positive value, even if the number of people is appropriate, it will not be opened until the time is right.
```
void CTFGameRules::SetupOnStalemateStart( void )
{
...
CArenaLogic *pArenaLogic = dynamic_cast< CArenaLogic * > (gEntList.FindEntityByClassname( NULL, "tf_logic_arena" ) );
if ( pArenaLogic )
{
pArenaLogic->m_OnArenaRoundStart.FireOutput( pArenaLogic, pArenaLogic );
if ( tf_arena_override_cap_enable_time.GetFloat() > 0 )
{
m_flCapturePointEnableTime = …
```

freak_fortress_2: Fix unlocking capture point is not working

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

Fixes:
* Sometimes weapon switching doesn't happen (`use %s` doesn't always permit that)
* Switching from minigun while revved up causing slowdown
Code calls `SetEntPropEnt(client, Prop_Send, "m_hActiveWeapon", other);` all the time, since `TF2Util_SetPlayerActiveWeapon` may not switch weapons sometimes, so it acts as a fallback. At least
`TF2Util_SetPlayerActiveWeapon` always calls the necessary weapon switching hooks (so I guess it works similar to `use %s`, without needing classnames and other overheads applied).
This should fix https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/issues/141

Fix switching to previous weapon not working correctly

---

addons/sourcemod/gamedata/ff2.txt
addons/sourcemod/scripting/ff2r_default_abilities.sp

I found a bug that minicrit doesn't applied with `mod mini-crit airborne` on super-jumping boss.
The reason for that was discovered after the decompiling latest server.so.
```
bool CTFGameRules::ApplyOnDamageModifyRules() {
...
int iMiniCritAirborne = 0;
CALL_ATTRIB_HOOK_INT_ON_OTHER( pWeapon, iMiniCritAirborne, mini_crit_airborne );
if ( iMiniCritAirborne == 1 && pVictim && ( ( !(GetFlags() & FL_ONGROUND) && (GetWaterLevel() == WL_NotInWater) && (m_iBlastJumpState != 0) ) || pVictim->m_Shared.InCond( TF_COND_KNOCKED_INTO_AIR ) ) )
{
bAllSeeCrit = true;
info.SetCritType( CTakeDamageInfo::CRIT_MINI );
eBonusEffect = kBonusEffect_MiniCrit;
break;
}
...
}
```
Other attributes related to blast-jumping such as `rocketjump attackrate bonus` only check `TFCond_BlastJumping`.
But `mod mini-crit …

Setting m_iBlastJumpState on superjump

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

Add parameter to rage_cloneattack to allow bosses to become minions

---

addons/sourcemod/scripting/freak_fortress_2/forwards_old.sp

The story:
We use hidden spawning plugin which spawns hidden bosses randomly, the plugin was made for FF2Bat. When one of the hidden bosses spawns, `characterName` was set to for example `hiddens/supremex10` (aka the path to the boss config) and everything worked fine.
The same plugin was tested on FF2R and It didn't work correctly, hidden boss will randomly not get forced. It seems FF2R only checks the `name` of the boss. Ok, then. I modified the plugin to set `characterName` to exact boss name. Tested and it also didn't work all the time. Fine. More code checking and it seems `OnSpecialSelected` uses inexact boss name matching. So I switched second argument to `true`
So there's the pull request, do exact boss name checking in `OnSpecialSelected`.

Do exact boss name matching in OnSpecialSelected

---

addons/sourcemod/scripting/freak_fortress_2/attributes.sp
addons/sourcemod/scripting/freak_fortress_2/weapons.sp

Known Bugs:
- Minicrit gained by `mod crit type on bosses` override normal critical(ex. headshot, flare).
- Air strike's projectile deal minicrit while rocket jump even if crit-boosted.
Fix:
- In `CTFGameRules::ApplyOnDamageModifyRules`, if damage type has `DMG_CRIT`, critType will change to 2(Crit_Full).
- In FF2R, if `OnTakeDamage` library doesn't exist, check damage type is DMG_CRIT. But library exist, only check critType.
- But most situation need to check damage type. Because critType will be determined in `CTFGameRules::ApplyOnDamageModifyRules`.
- So I added damage type check.
- Still attribute 410 is not fixed..
This should fix #138.

Fix crit type limit

---

addons/sourcemod/scripting/freak_fortress_2/weapons.sp

- "slot damage vs bosses" doesn't applied to weapon if it hasn't any custom attributes.

Fixed "slot damage vs bosses"

---

addons/sourcemod/scripting/ff2r_default_abilities.sp
addons/sourcemod/scripting/freak_fortress_2/stocks.sp

In decomplied `TranslateWeaponEntForClass` and `pszWpnEntTranslationList`,
```
.data:01787510                 dd offset aSaxxy        ; "saxxy"
.data:01787514                 dd offset unk_140F41A - TFClass_Unknown
.data:01787518                 dd offset aTfWeaponBat  ; "tf_weapon_bat" - TFClass_Scout
.data:0178751C                 dd offset aTfWeaponClub ; "tf_weapon_club" - TFClass_Sniper
.data:01787520                 dd offset aTfWeaponShovel ; "tf_weapon_shovel" - TFClass_Soldier
.data:01787524                 dd offset aTfWeaponBottle ; "tf_weapon_bottle" - TFClass_Demoman
.data:01787528                 dd offset aTfWeaponBonesa ; "tf_weapon_bonesaw" - TFClass_Medic
.data:0178752C                 dd offset aTfWeaponFireax ; "tf_weapon_fireaxe" - TFClass_Heavy
.data:01787530 …
```

Fixed wrong classname in GetClassWeaponClassname

---

addons/sourcemod/scripting/ff2r_default_abilities.sp
addons/sourcemod/translations/ff2_rewrite.phrases.txt

Unlike the abilties(`special_walljump`, ...) in the ff2r_epic_abilities, `special_democharge` doesn't have hint on round start. I made it because people who use demopan don't know that it's possible to charge. And I added support to use more button for it.

ff2r_default_abilities: Add hint for `special_democharge` and support another button

---

addons/sourcemod/scripting/freak_fortress_2/gamemode.sp

- "Can't joining any team" issue was fixed on Various Fixes. But gamemode.sp still use old detect method. As a result, it skips "waiting for player" phase.

freak_fortress_2: Fix waitingforplayer phase skipping

---

addons/sourcemod/scripting/freak_fortress_2/events.sp

- It was unintentional left out feature.
- TODO: Add ConVar to prevent to activate slot 4 when fake death?

freak_fortress_2: Reimplement ability slot 4

---

addons/sourcemod/gamedata/ff2.txt
addons/sourcemod/scripting/freak_fortress_2/attributes.sp
addons/sourcemod/scripting/freak_fortress_2/sdkcalls.sp

- Increased velocity to proper dispersal of medikit(too low to spread).
- I used `CTFPowerup::DropSingleInstance`. It's not good to chase game updates with functions.
- `CTFPowerup::DropSingleInstance` has unique x-ref string `"PowerupRemoveThink"`.
Fixes #168.

freak_fortress_2: Fix dropping `item_healthkit_small`

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

There'll be a followup PR which will specify whether minions will spawn in spawn or not.

ff2r_default_abilities: Add 'rival' to specify whether minion will respawn on rival team

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

Players spawned through rage_cloneattack will appear in spawn. Useful when 'rival' is 1 so as to prevent the player from being stuck as well as other purposes.

ff2r_default_abilities: Add "move to spawn"

---

README.md
addons/sourcemod/scripting/freak_fortress_2.sp
addons/sourcemod/scripting/freak_fortress_2/attributes.sp
addons/sourcemod/scripting/freak_fortress_2/bosses.sp
addons/sourcemod/scripting/freak_fortress_2/commands.sp
addons/sourcemod/scripting/freak_fortress_2/configs.sp
addons/sourcemod/scripting/freak_fortress_2/convars.sp
addons/sourcemod/scripting/freak_fortress_2/database.sp
addons/sourcemod/scripting/freak_fortress_2/dhooks.sp
addons/sourcemod/scripting/freak_fortress_2/events.sp
addons/sourcemod/scripting/freak_fortress_2/filenetwork.sp
addons/sourcemod/scripting/freak_fortress_2/gamemode.sp
addons/sourcemod/scripting/freak_fortress_2/menu.sp
addons/sourcemod/scripting/freak_fortress_2/music.sp
addons/sourcemod/scripting/freak_fortress_2/natives.sp
addons/sourcemod/scripting/freak_fortress_2/natives_old.sp
addons/sourcemod/scripting/freak_fortress_2/preference.sp
addons/sourcemod/scripting/freak_fortress_2/sdkhooks.sp
addons/sourcemod/scripting/freak_fortress_2/stocks.sp
addons/sourcemod/scripting/freak_fortress_2/weapons.sp
addons/sourcemod/scripting/include/ff2r.inc
addons/sourcemod/translations/ff2_rewrite.phrases.txt
scripts/optional.sh

Adds support for using [File Network](https://github.com/Batfoxkid/File-Network) as an alternative for boss downloads, especially sound files. This will help in some cases where you may need to reduce entry downloads or things that may be optional like alternative music or catch phrases. Any file is supported but models are not handled by FF2 or anything that does not play from FF2. A new native `FF2R_ClientHasFile` is available for these cases.
Automatically checks in sound section files whether to play the sound (or display an overlay) to a player.
The example below shows making the music file download in-game, since it's used by sound_bgm, it'll wait until the player has the sound before playing the music.
```diff
"download"
{
"models/freak_fortress_2/gentlespy/the_gentlespy_v3" …
```

File Network for Boss Downloads

---

addons/sourcemod/scripting/ff2r_epic_abilities.sp
addons/sourcemod/translations/ff2_rewrite.phrases.txt

- Originally, description in AMS is appeared while ducking. But this way isn't good because ducking is very frequent in tf2(ex: duck-jump). As a result, AMS HUD is very messy to looking.
- So, I changed that to use `+inspect`(Default: F).

Use `+inspect` instead of ducking to show ability's description

---

addons/sourcemod/scripting/freak_fortress_2.sp
addons/sourcemod/scripting/freak_fortress_2/bosses.sp
addons/sourcemod/scripting/freak_fortress_2/gamemode.sp

Fixes FF2 never loading on workshop maps by adding GetMapDisplayName.

Fix for FF2 not recognizing workshop maps

---

addons/sourcemod/scripting/freak_fortress_2/configs.sp

- #252 allow FF2 to load workshop map. However, the bug where a pack vote was not created when a Workshop map was selected as the next map still remained.
- Thanks to @synthakii for letting me know about this issue.

Fix Pack Vote for workshop map

---

addons/sourcemod/gamedata/ff2.txt

- Removed `m_iBlastJumpState` offset. `CTFPlayer::SetBlastJumpState` is replaced it.

Gamedata Update for TF2 2025-05-01 update

---

addons/sourcemod/scripting/ff2r_default_abilities.sp

For some unknown reason, adding `TFCond_BlastJumping` condition disrupts applying `m_iBlastJumpState`.

Fix not applying blastjumpstate when superjump
